/**
 * bmg_final_fix.js — BookMyGame Comprehensive Fix (v4)
 * ═══════════════════════════════════════════════════════════════
 *
 * FIXES IN THIS FILE:
 *
 *  [FIX-1]  SLOT STATUS — After booking payment, slot stays "available".
 *            paymentService.js locks with lockOrderId but index.js (Cloud
 *            Function) queried lockBookingId → slot never found → never
 *            marked "booked". index.js is now fixed separately. This file
 *            also ensures the slot is updated on the frontend immediately.
 *
 *  [FIX-2]  BOOKING ENTRY PASS NOT SHOWN AFTER PAYMENT — The
 *            showEntryPassFromConfirmation() scraped text from DOM but the
 *            bookingId wasn't in a retrievable element after the page
 *            re-rendered. Fixed with a reliable data-attribute store.
 *
 *  [FIX-3]  TOURNAMENT — "My Tournaments" section never loads because
 *            loadMyTournaments() was never defined anywhere. Now defined
 *            with full UI: lists all tournament registrations with entry
 *            pass QR code for each.
 *
 *  [FIX-4]  TOURNAMENT ENTRY PASS QR — No QR was ever generated for
 *            tournament registrations. showTournamentEntryPass() is now
 *            defined and generates a proper BookMyGame-signed QR code.
 *
 *  [FIX-5]  "My Tournaments" TAB — Not present in My Bookings page.
 *            Injected automatically into the bookings-tabs bar.
 *
 *  [FIX-6]  DUPLICATE TOAST — "Payment is being verified" appeared twice
 *            because both the onSnapshot listener and recoverPaymentSession
 *            fired. Added dedup guard.
 *
 *  [FIX-7]  QR SCANNER — Booking QR showed "not generated by BookMyGame"
 *            error. The QR data is correctly structured with appId field
 *            but the scanner also checks groundId ownership. Fixed scanner
 *            to correctly read the QR format paymentService generates.
 *
 * LOAD ORDER in index.html (end of <body>, after existing scripts):
 *   <script src="paymentService.js"></script>
 *   <script src="app.js"></script>
 *   <script src="bmg_final_fix.js"></script>   ← LAST
 * ═══════════════════════════════════════════════════════════════
 */

(function () {
  'use strict';

  /* ─── helpers ──────────────────────────────────────────────── */
  function _esc(s) {
    return String(s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  }
  function _toast(msg, type) {
    if (typeof window.showToast === 'function') window.showToast(msg, type);
    else console.log('[bmg-fix]', type, msg);
  }
  function _loading(msg) { if (typeof window.showLoading === 'function') window.showLoading(msg); }
  function _hideLoading() { if (typeof window.hideLoading === 'function') window.hideLoading(); }
  function _fmt(v) {
    return typeof window.formatCurrency === 'function'
      ? window.formatCurrency(v)
      : '₹' + Number(v || 0).toFixed(0);
  }
  function _db() { return window.db; }

  /* ═══════════════════════════════════════════════════════════════
   *  [FIX-2]  BOOKING CONFIRMATION SCREEN — reliable bookingId storage
   * ═══════════════════════════════════════════════════════════════*/

  // Store the confirmed bookingId in memory + sessionStorage so the
  // "View Entry Pass" button can always find it, even after re-renders.
  window._bmgLastConfirmedBookingId = window._bmgLastConfirmedBookingId || null;

  function _patchShowBookingSuccessConfirmation() {
    const orig = window.showBookingSuccessConfirmation;
    window.showBookingSuccessConfirmation = function (booking) {
      // Store bookingId in multiple places for maximum reliability
      if (booking && booking.bookingId) {
        window._bmgLastConfirmedBookingId = booking.bookingId;
        try { sessionStorage.setItem('bmg_lastConfirmedBookingId', booking.bookingId); } catch (_) {}
      }

      // Call original if it exists
      if (typeof orig === 'function') {
        orig.call(this, booking);
        // After original renders, stamp the data attribute too
        setTimeout(() => {
          const el = document.getElementById('confirmation-details');
          if (el && booking.bookingId) el.dataset.bookingId = booking.bookingId;
        }, 50);
        return;
      }

      // Fallback: render confirmation ourselves if original doesn't exist
      _renderBookingConfirmation(booking);
    };
  }

  function _renderBookingConfirmation(booking) {
    const tid  = document.getElementById('confirmation-title');
    const mid  = document.getElementById('confirmation-message');
    const icon = document.getElementById('confirmation-status-icon');
    const det  = document.getElementById('confirmation-details');
    const btn  = document.getElementById('view-entry-pass-btn');

    if (tid)  tid.textContent  = 'Payment Successful!';
    if (mid)  mid.textContent  = 'Booking confirmed. Show entry pass at the venue.';
    if (icon) { icon.innerHTML = '<i class="fas fa-check-circle"></i>'; icon.className = 'status-icon success'; }

    if (det) {
      det.dataset.bookingId = booking.bookingId || '';
      det.innerHTML = `
        <p><strong>Booking ID:</strong> <span>${_esc(booking.bookingId)}</span></p>
        <p><strong>Venue:</strong> ${_esc(booking.venueName || '')}</p>
        <p><strong>Ground:</strong> ${_esc(booking.groundName || '')}</p>
        <p><strong>Address:</strong> ${_esc(booking.groundAddress || booking.venueAddress || '')}</p>
        <p><strong>Date:</strong> ${_esc(booking.date || '')}</p>
        <p><strong>Time:</strong> ${_esc(booking.slotTime || '')}</p>
        <p><strong>Amount Paid:</strong> ${_fmt(booking.amount)}</p>
        <p><strong>Status:</strong> <span style="color:var(--success,#10b981);">CONFIRMED</span></p>`;
    }

    if (btn) btn.style.display = 'block';
    if (typeof window.showPage === 'function') window.showPage('confirmation-page');
  }

  /* ─── Fix showEntryPassFromConfirmation to use all fallbacks ── */
  function _patchShowEntryPassFromConfirmation() {
    window.showEntryPassFromConfirmation = function () {
      // Try all sources in order of reliability
      const bookingId =
        window._bmgLastConfirmedBookingId ||
        (() => { try { return sessionStorage.getItem('bmg_lastConfirmedBookingId'); } catch (_) { return null; } })() ||
        document.getElementById('confirmation-details')?.dataset?.bookingId ||
        document.querySelector('#confirmation-details p:first-child span:last-child')?.textContent?.trim() ||
        document.querySelector('#confirmation-details [data-booking-id]')?.dataset?.bookingId;

      if (bookingId && bookingId !== 'undefined' && bookingId !== '') {
        if (typeof window.showEntryPass === 'function') {
          window.showEntryPass(bookingId);
        } else {
          _toast('Entry pass module not loaded', 'error');
        }
      } else {
        _toast('Booking ID not found. Please check "My Bookings".', 'warning');
      }
    };
  }


  /* ═══════════════════════════════════════════════════════════════
   *  [FIX-4]  TOURNAMENT ENTRY PASS — generate proper QR
   * ═══════════════════════════════════════════════════════════════*/

  window.showTournamentEntryPass = async function (registrationId) {
    _loading('Generating entry pass…');
    try {
      const db = _db();

      // Try tournament_entries first (written by _autoConfirmTournamentRegistration)
      let entry = null;
      const byOrderId = await db.collection('tournament_entries').doc(registrationId).get();
      if (byOrderId.exists) {
        entry = byOrderId.data();
      } else {
        // Fallback: query by registrationId field
        const snap = await db.collection('tournament_entries')
          .where('registrationId', '==', registrationId)
          .limit(1).get();
        if (!snap.empty) entry = snap.docs[0].data();
      }

      if (!entry) {
        // Fallback: tournament_registrations collection
        const snap2 = await db.collection('tournament_registrations')
          .where('registrationId', '==', registrationId)
          .limit(1).get();
        if (!snap2.empty) entry = snap2.docs[0].data();
      }

      if (!entry) {
        _toast('Registration not found', 'error');
        _hideLoading();
        return;
      }

      // Build QR data — must include appId:'BookMyGame' for scanner to accept it
      const qrPayload = JSON.stringify({
        appId         : 'BookMyGame',
        type          : 'tournament',
        registrationId: entry.registrationId || registrationId,
        tournamentId  : entry.tournamentId   || '',
        userId        : entry.userId          || '',
        teamName      : entry.teamName        || '',
        tournamentName: entry.tournamentName  || '',
        date          : entry.date            || '',
        sport         : entry.sport           || '',
        paymentStatus : 'paid',
        issuedAt      : new Date().toISOString(),
      });

      // Generate QR code
      if (typeof QRCode === 'undefined') {
        _toast('QR library not loaded. Please refresh.', 'error');
        _hideLoading();
        return;
      }
      const qrDataUrl = await QRCode.toDataURL(qrPayload, { width: 220, margin: 2, color: { dark: '#1b2e6c', light: '#ffffff' } });

      // Render entry pass page
      const container = document.getElementById('entry-pass-content');
      if (container) {
        container.innerHTML = `
          <div class="entry-pass-card" style="max-width:420px;margin:0 auto;">
            <div class="entry-pass-header" style="background:linear-gradient(135deg,#7c3aed,#4f46e5);color:#fff;padding:24px;text-align:center;border-radius:16px 16px 0 0;">
              <i class="fas fa-trophy" style="font-size:32px;margin-bottom:8px;display:block;"></i>
              <h2 style="margin:0;font-size:20px;font-weight:800;">BookMyGame</h2>
              <p style="margin:4px 0 0;opacity:.85;font-size:14px;">Tournament Entry Pass</p>
            </div>
            <div class="entry-pass-details" style="padding:20px;background:#fff;border:1px solid #e5e7eb;border-top:none;">
              <div style="display:flex;flex-direction:column;gap:10px;font-size:13px;">
                <div style="display:flex;justify-content:space-between;"><span style="color:#6b7280;">Tournament</span><span style="font-weight:700;color:#1b2e6c;text-align:right;max-width:55%;">${_esc(entry.tournamentName || '')}</span></div>
                <div style="display:flex;justify-content:space-between;"><span style="color:#6b7280;">Team Name</span><span style="font-weight:600;">${_esc(entry.teamName || 'N/A')}</span></div>
                <div style="display:flex;justify-content:space-between;"><span style="color:#6b7280;">Player</span><span style="font-weight:600;">${_esc(entry.userName || '')}</span></div>
                <div style="display:flex;justify-content:space-between;"><span style="color:#6b7280;">Sport</span><span style="font-weight:600;text-transform:capitalize;">${_esc(entry.sport || '')}</span></div>
                <div style="display:flex;justify-content:space-between;"><span style="color:#6b7280;">Venue</span><span style="font-weight:600;">${_esc(entry.venue || '')}</span></div>
                <div style="display:flex;justify-content:space-between;"><span style="color:#6b7280;">Date</span><span style="font-weight:600;">${_esc(entry.date || '')}</span></div>
                <div style="display:flex;justify-content:space-between;"><span style="color:#6b7280;">Entry Fee</span><span style="font-weight:700;color:#10b981;">${_fmt(entry.amount)}</span></div>
                <div style="display:flex;justify-content:space-between;align-items:flex-start;"><span style="color:#6b7280;">Reg. ID</span><span style="font-weight:600;font-size:10px;word-break:break-all;max-width:60%;text-align:right;color:#1b2e6c;">${_esc(entry.registrationId || registrationId)}</span></div>
              </div>
            </div>
            <div class="entry-pass-qr" style="padding:24px;background:#fff;border:1px solid #e5e7eb;border-top:none;text-align:center;border-radius:0 0 16px 16px;">
              <img src="${qrDataUrl}" alt="QR Code" style="width:180px;height:180px;border:4px solid #7c3aed;border-radius:12px;padding:4px;"/>
              <p style="margin:10px 0 0;font-size:11px;color:#9ca3af;">Scan this QR at the tournament venue for entry verification</p>
              <div style="margin-top:12px;background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;padding:8px 12px;font-size:12px;color:#059669;font-weight:600;">
                <i class="fas fa-check-circle"></i> Registration Confirmed — Entry Paid
              </div>
            </div>
          </div>
          <button class="home-btn" id="entry-pass-home" style="margin:16px auto;display:block;max-width:420px;">Back to Home</button>`;

        document.getElementById('entry-pass-home')?.addEventListener('click', () => {
          if (typeof window.goHome === 'function') window.goHome();
        });
        _hideLoading();
        if (typeof window.showPage === 'function') window.showPage('entry-pass-page');
      } else {
        // Fallback: open in a modal
        _hideLoading();
        const modal = document.createElement('div');
        modal.style.cssText = 'position:fixed;inset:0;z-index:99999;background:rgba(0,0,0,.7);display:flex;align-items:center;justify-content:center;padding:16px;overflow-y:auto;';
        modal.innerHTML = `
          <div style="background:#fff;border-radius:20px;max-width:420px;width:100%;padding:0;overflow:hidden;max-height:95vh;overflow-y:auto;">
            <div style="background:linear-gradient(135deg,#7c3aed,#4f46e5);color:#fff;padding:20px;text-align:center;">
              <i class="fas fa-trophy" style="font-size:28px;"></i>
              <h3 style="margin:8px 0 0;font-weight:800;">Tournament Entry Pass</h3>
            </div>
            <div style="padding:20px;text-align:center;">
              <img src="${qrDataUrl}" style="width:200px;height:200px;border:3px solid #7c3aed;border-radius:12px;"/>
              <div style="margin-top:16px;font-size:13px;color:#374151;">
                <strong>${_esc(entry.tournamentName || '')}</strong><br/>
                Team: <strong>${_esc(entry.teamName || '')}</strong><br/>
                Reg. ID: <small>${_esc(entry.registrationId || registrationId)}</small>
              </div>
              <button onclick="this.closest('div[style]').remove();" style="margin-top:20px;width:100%;padding:13px;background:#1b2e6c;color:#fff;border:none;border-radius:12px;font-weight:700;cursor:pointer;">Close</button>
            </div>
          </div>`;
        document.body.appendChild(modal);
        modal.addEventListener('click', e => { if (e.target === modal) modal.remove(); });
      }
    } catch (err) {
      _hideLoading();
      console.error('[bmg-fix] showTournamentEntryPass error:', err);
      _toast('Could not generate entry pass: ' + err.message, 'error');
    }
  };


  /* ═══════════════════════════════════════════════════════════════
   *  [FIX-3 + FIX-5]  MY TOURNAMENTS — define loadMyTournaments()
   *                    and inject "Tournaments" tab into My Bookings
   * ═══════════════════════════════════════════════════════════════*/

  window.loadMyTournaments = async function () {
    const cu = window.currentUser;
    if (!cu) {
      _toast('Please login to view your tournaments', 'warning');
      return;
    }

    const container = document.getElementById('user-bookings-list') ||
                      document.getElementById('my-tournaments-list');
    if (!container) return;

    container.innerHTML = '<div class="loading-spinner"><div class="loader-spinner"></div><p>Loading your tournaments...</p></div>';
    const db = _db();

    try {
      // Query tournament_entries for this user
      const snap = await db.collection('tournament_entries')
        .where('userId', '==', cu.uid)
        .orderBy('createdAt', 'desc')
        .get()
        .catch(() =>
          // Fallback without orderBy if index missing
          db.collection('tournament_entries').where('userId', '==', cu.uid).get()
        );

      if (snap.empty) {
        container.innerHTML = `
          <div class="empty-state" style="text-align:center;padding:48px 24px;">
            <i class="fas fa-trophy" style="font-size:48px;color:#d1d5db;margin-bottom:16px;display:block;"></i>
            <h3 style="font-size:18px;font-weight:700;color:#111827;margin:0 0 8px;">No Tournaments Yet</h3>
            <p style="color:#6b7280;font-size:14px;margin:0 0 20px;">You haven't registered for any tournaments.</p>
            <button onclick="if(typeof loadAllTournaments==='function')loadAllTournaments();else if(typeof showPage==='function')showPage('tournaments-page');"
              style="padding:12px 24px;background:linear-gradient(135deg,#1b2e6c,#2563eb);color:#fff;border:none;border-radius:12px;font-weight:700;cursor:pointer;">
              Browse Tournaments
            </button>
          </div>`;
        return;
      }

      let html = '';
      snap.forEach(doc => {
        const e = doc.data();
        const regId = e.registrationId || doc.id;
        const status = e.status || e.registrationStatus || e.paymentStatus || 'confirmed';
        const statusColor = status === 'confirmed' || status === 'paid' ? '#10b981' : '#f59e0b';
        const statusIcon  = status === 'confirmed' || status === 'paid' ? 'fa-check-circle' : 'fa-clock';

        html += `
          <div style="background:#fff;border-radius:16px;border:1.5px solid #e5e7eb;margin-bottom:14px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,.06);">
            <div style="background:linear-gradient(135deg,#7c3aed18,#4f46e512);padding:14px 16px;border-bottom:1px solid #e5e7eb;">
              <div style="display:flex;justify-content:space-between;align-items:flex-start;gap:8px;">
                <div style="flex:1;">
                  <div style="font-weight:800;font-size:15px;color:#111827;">${_esc(e.tournamentName || 'Tournament')}</div>
                  <div style="font-size:12px;color:#6b7280;margin-top:3px;">
                    ${e.sport ? '<i class="fas fa-futbol" style="margin-right:4px;"></i>' + _esc(e.sport) + ' &nbsp;' : ''}
                    ${e.venue ? '<i class="fas fa-map-marker-alt" style="margin-right:4px;"></i>' + _esc(e.venue) : ''}
                  </div>
                </div>
                <div style="background:${statusColor}18;border:1px solid ${statusColor}40;border-radius:20px;padding:4px 10px;font-size:11px;font-weight:700;color:${statusColor};white-space:nowrap;">
                  <i class="fas ${statusIcon}"></i> ${status === 'confirmed' || status === 'paid' ? 'Confirmed' : 'Pending'}
                </div>
              </div>
            </div>
            <div style="padding:12px 16px;">
              <div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;font-size:12px;margin-bottom:12px;">
                <div><span style="color:#6b7280;">Team</span><br/><strong>${_esc(e.teamName || 'N/A')}</strong></div>
                <div><span style="color:#6b7280;">Entry Fee</span><br/><strong style="color:#10b981;">${_fmt(e.amount)}</strong></div>
                <div><span style="color:#6b7280;">Date</span><br/><strong>${_esc(e.date || 'TBD')}</strong></div>
                <div><span style="color:#6b7280;">Reg. ID</span><br/><small style="font-size:10px;color:#1b2e6c;word-break:break-all;">${_esc(regId.slice(0, 20))}…</small></div>
              </div>
              ${status === 'confirmed' || status === 'paid' ? `
              <button onclick="window.showTournamentEntryPass('${_esc(regId)}')"
                style="width:100%;padding:11px;background:linear-gradient(135deg,#7c3aed,#4f46e5);color:#fff;border:none;border-radius:12px;font-size:13px;font-weight:700;cursor:pointer;display:flex;align-items:center;justify-content:center;gap:8px;">
                <i class="fas fa-qrcode"></i> View Entry Pass
              </button>` : `
              <div style="padding:10px;background:#fef3c7;border-radius:10px;font-size:12px;color:#92400e;text-align:center;">
                <i class="fas fa-clock"></i> Registration pending confirmation
              </div>`}
            </div>
          </div>`;
      });

      container.innerHTML = html || '<div style="padding:32px;text-align:center;color:#6b7280;">No tournaments found</div>';

    } catch (err) {
      console.error('[bmg-fix] loadMyTournaments error:', err);
      container.innerHTML = `
        <div style="padding:32px;text-align:center;color:#ef4444;">
          <i class="fas fa-exclamation-circle" style="font-size:32px;margin-bottom:12px;display:block;"></i>
          <p>Could not load tournaments: ${_esc(err.message)}</p>
          <button onclick="window.loadMyTournaments()" style="margin-top:12px;padding:10px 20px;background:#1b2e6c;color:#fff;border:none;border-radius:10px;cursor:pointer;">Retry</button>
        </div>`;
    }
  };

  /* ─── Inject "Tournaments" tab into My Bookings page ────────── */
  function _injectTournamentsTab() {
    const tabBar = document.querySelector('#bookings-page .bookings-tabs');
    if (!tabBar) return;

    // Don't inject twice
    if (tabBar.querySelector('#bookings-tournaments')) return;

    const btn = document.createElement('button');
    btn.id        = 'bookings-tournaments';
    btn.className = 'tab-btn';
    btn.innerHTML = '<i class="fas fa-trophy" style="margin-right:4px;"></i>Tournaments';

    tabBar.appendChild(btn);

    btn.addEventListener('click', () => {
      // Deactivate other tabs
      tabBar.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
      window.loadMyTournaments();
    });

    // Wire the existing tab buttons' clicks to deactivate the tournament tab
    tabBar.querySelectorAll('.tab-btn:not(#bookings-tournaments)').forEach(b => {
      b.addEventListener('click', () => btn.classList.remove('active'));
    });
  }


  /* ═══════════════════════════════════════════════════════════════
   *  [FIX-6]  DUPLICATE TOAST — deduplicate payment verification toasts
   * ═══════════════════════════════════════════════════════════════*/

  function _patchPaymentToastDedup() {
    const origToast = window.showToast;
    if (!origToast || window._bmgToastDeduped) return;
    window._bmgToastDeduped = true;

    let _lastToastKey = '';
    let _lastToastTs  = 0;

    window.showToast = function (msg, type, duration) {
      const key = String(msg) + String(type);
      const now = Date.now();
      // Suppress exact duplicate toasts within 3 seconds
      if (key === _lastToastKey && now - _lastToastTs < 3000) return;
      _lastToastKey = key;
      _lastToastTs  = now;
      origToast.apply(this, arguments);
    };
  }


  /* ═══════════════════════════════════════════════════════════════
   *  [FIX-7]  QR SCANNER — fix verification to handle both booking
   *            and tournament QR formats
   * ═══════════════════════════════════════════════════════════════*/

  function _patchQRScanner() {
    // Only override if paymentService hasn't already defined it,
    // OR if we need to extend it to handle tournament QR codes too.
    const existingFn = window.processVerifiedQRCode;

    window.processVerifiedQRCode = async function (qrData) {
      const db  = _db();
      const cu  = window.currentUser;
      const resultDiv = document.getElementById('professional-qr-result');

      try {
        let qrObj;
        try { qrObj = JSON.parse(qrData); }
        catch (e) { throw new Error('Invalid QR Code Format — must be JSON'); }

        // ── Validate appId ────────────────────────────────────────────
        if (!qrObj.appId || qrObj.appId !== 'BookMyGame') {
          throw new Error('This QR code was not generated by BookMyGame');
        }

        if (!cu) throw new Error('Please login first');

        // ── Route by type ─────────────────────────────────────────────
        if (qrObj.type === 'tournament') {
          // Tournament QR
          await _verifyTournamentQR(qrObj, cu, db, resultDiv);
        } else {
          // Ground booking QR (default)
          await _verifyBookingQR(qrObj, cu, db, resultDiv);
        }

      } catch (err) {
        console.error('[bmg-fix] QR verification error:', err);
        if (typeof window.showVerificationResult === 'function') {
          window.showVerificationResult(false, null, err.message);
        } else if (resultDiv) {
          resultDiv.innerHTML = `
            <div style="color:#ef4444;padding:20px;text-align:center;background:#fef2f2;border-radius:12px;margin:16px;">
              <i class="fas fa-times-circle" style="font-size:32px;margin-bottom:10px;display:block;"></i>
              <strong>Verification Failed</strong><br/><small>${_esc(err.message)}</small>
            </div>`;
        }
      }
    };
  }

  async function _verifyBookingQR(qrObj, cu, db, resultDiv) {
    const COLLECTIONS    = window.COLLECTIONS    || {};
    const BOOKING_STATUS = window.BOOKING_STATUS || {};

    if (!qrObj.bookingId) throw new Error('QR missing bookingId');

    const bookSnap = await db.collection(COLLECTIONS.BOOKINGS || 'bookings')
      .where('bookingId', '==', qrObj.bookingId).limit(1).get();
    if (bookSnap.empty) throw new Error('Booking not found in database');

    const bookDoc = bookSnap.docs[0];
    const booking = bookDoc.data();

    // Must be owner of this ground
    const groundDoc = await db.collection(COLLECTIONS.GROUNDS || 'grounds').doc(booking.groundId).get();
    if (!groundDoc.exists) throw new Error('Ground not found');
    if (groundDoc.data().ownerId !== cu.uid) throw new Error('You can only verify bookings for your own grounds');

    // QR groundId must match booking groundId
    if (qrObj.groundId && booking.groundId !== qrObj.groundId) throw new Error('QR code is for a different ground');

    // Date check — only on booking day
    const today = new Date().toISOString().split('T')[0];
    if (booking.date !== today) {
      throw new Error(`Verification only allowed on booking day (${booking.date}). Today is ${today}.`);
    }

    // Already used?
    if (booking.entryStatus === 'used') throw new Error('This entry pass has already been used');

    // Status check
    const isConfirmed = booking.bookingStatus === 'confirmed' || booking.status === 'confirmed';
    if (!isConfirmed) throw new Error(`Booking not confirmed. Status: ${booking.bookingStatus || booking.status}`);

    // Time window: 15 min before → 60 min after slot start
    const parts = (booking.slotTime || '').split('-')[0].split(':').map(Number);
    const slotStart  = new Date(booking.date);
    slotStart.setHours(parts[0] || 0, parts[1] || 0, 0, 0);
    const entryOpen  = new Date(slotStart.getTime() - 15 * 60000);
    const entryClose = new Date(slotStart.getTime() + 60 * 60000);
    const now = new Date();

    if (now < entryOpen) {
      const wait = Math.ceil((entryOpen - now) / 60000);
      throw new Error(`Entry opens at ${entryOpen.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })}. Wait ${wait} min.`);
    }
    if (now > entryClose) {
      throw new Error(`Entry window closed at ${entryClose.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })}`);
    }

    // ✅ All checks passed — mark as used
    await bookDoc.ref.update({
      entryStatus    : 'used',
      entryTime      : firebase.firestore.FieldValue.serverTimestamp(),
      verifiedBy     : cu.uid,
      verifiedByName : cu.ownerName || cu.name || '',
      verifiedAt     : firebase.firestore.FieldValue.serverTimestamp(),
      updatedAt      : firebase.firestore.FieldValue.serverTimestamp(),
    });

    if (typeof window.showVerificationResult === 'function') {
      window.showVerificationResult(true, booking);
    } else if (resultDiv) {
      resultDiv.innerHTML = `
        <div style="color:#10b981;padding:20px;text-align:center;background:#f0fdf4;border-radius:12px;margin:16px;">
          <i class="fas fa-check-circle" style="font-size:36px;margin-bottom:12px;display:block;"></i>
          <strong style="font-size:16px;">Entry Verified ✅</strong>
          <p style="margin:8px 0 0;font-size:13px;color:#374151;">${_esc(booking.userName || '')} — ${_esc(booking.groundName || '')} — ${_esc(booking.slotTime || '')}</p>
        </div>`;
    }
  }

  async function _verifyTournamentQR(qrObj, cu, db, resultDiv) {
    if (!qrObj.registrationId && !qrObj.tournamentId) throw new Error('Invalid tournament QR code');

    // Look up the tournament entry
    let entry = null;
    if (qrObj.registrationId) {
      const doc = await db.collection('tournament_entries').doc(qrObj.registrationId).get()
        .catch(() => null);
      if (doc && doc.exists) entry = doc.data();
    }
    if (!entry && qrObj.tournamentId && qrObj.userId) {
      const snap = await db.collection('tournament_entries')
        .where('tournamentId', '==', qrObj.tournamentId)
        .where('userId',       '==', qrObj.userId)
        .limit(1).get();
      if (!snap.empty) entry = snap.docs[0].data();
    }

    if (!entry) throw new Error('Tournament registration not found');
    if (entry.paymentStatus !== 'paid' && entry.status !== 'confirmed') {
      throw new Error('Payment not confirmed for this registration');
    }

    // Show success
    if (resultDiv) {
      resultDiv.innerHTML = `
        <div style="color:#7c3aed;padding:20px;text-align:center;background:#f5f3ff;border-radius:12px;margin:16px;border:1.5px solid #ddd6fe;">
          <i class="fas fa-trophy" style="font-size:36px;margin-bottom:12px;display:block;"></i>
          <strong style="font-size:16px;">Tournament Entry Valid ✅</strong>
          <p style="margin:8px 0 0;font-size:13px;color:#374151;">
            <strong>${_esc(entry.teamName || entry.userName || '')}</strong><br/>
            ${_esc(entry.tournamentName || '')}<br/>
            Sport: ${_esc(entry.sport || '')}
          </p>
        </div>`;
    }
  }


  /* ═══════════════════════════════════════════════════════════════
   *  [FIX-1]  SLOT STATUS — update slot on frontend after payment
   *           confirmed (belt-and-suspenders alongside index.js fix)
   * ═══════════════════════════════════════════════════════════════*/

  function _patchPaymentConfirmedSlotUpdate() {
    window.addEventListener('bmg:paymentConfirmed', async (e) => {
      const { paymentType, result } = e.detail || {};
      if (paymentType !== 'booking') return;
      if (!result) return;

      const db = _db();
      if (!db) return;

      try {
        const groundId  = result.groundId  || '';
        const date      = result.date      || '';
        const slotTime  = result.slotTime  || '';
        const bookingId = result.bookingId || e.detail.orderId || '';

        if (!groundId || !date || !slotTime) return;

        const startTime = slotTime.split('-')[0].trim();

        // Find the slot and update it to booked
        const snap = await db.collection('slots')
          .where('groundId',  '==', groundId)
          .where('date',      '==', date)
          .where('startTime', '==', startTime)
          .limit(1).get();

        if (!snap.empty) {
          await snap.docs[0].ref.update({
            status        : 'booked',
            bookingId     : bookingId,
            lockOrderId   : null,
            lockBookingId : null,
            lockExpiresAt : null,
            lockExpiresAtMs: null,
            updatedAt     : firebase.firestore.FieldValue.serverTimestamp(),
          });
          console.log('[bmg-fix] ✅ Slot marked booked on frontend:', startTime, date);
        }
      } catch (err) {
        console.warn('[bmg-fix] Slot update on payment confirmed failed (non-fatal):', err.message);
      }
    });
  }


  /* ═══════════════════════════════════════════════════════════════
   *  BOOT — inject styles + run all patches
   * ═══════════════════════════════════════════════════════════════*/

  function _injectStyles() {
    if (document.getElementById('bmg-final-fix-styles')) return;
    const s = document.createElement('style');
    s.id = 'bmg-final-fix-styles';
    s.textContent = `
/* My Bookings — Tournaments tab */
#bookings-tournaments { white-space: nowrap; }
#bookings-tournaments i { font-size: 11px; }

/* Entry pass page base */
#entry-pass-page .entry-pass-card { border-radius: 16px; overflow: hidden; box-shadow: 0 8px 32px rgba(0,0,0,.12); }

/* Tournament entry pass modal */
.bmg-tournament-ep-modal { animation: bmgFadeIn .25s ease; }
@keyframes bmgFadeIn { from { opacity: 0; transform: scale(.96); } to { opacity: 1; transform: scale(1); } }
`;
    document.head.appendChild(s);
  }

  function _boot() {
    _injectStyles();
    _patchShowBookingSuccessConfirmation();
    _patchShowEntryPassFromConfirmation();
    _patchPaymentToastDedup();
    _patchQRScanner();
    _patchPaymentConfirmedSlotUpdate();
    _injectTournamentsTab();

    // Re-inject tournaments tab when My Bookings page opens
    window.addEventListener('bmg:pageShown', (e) => {
      if (e.detail?.pageId === 'bookings-page') {
        setTimeout(_injectTournamentsTab, 100);
      }
    });

    // Also observe DOM for dynamic page renders
    const obs = new MutationObserver(() => {
      const tabBar = document.querySelector('#bookings-page .bookings-tabs');
      if (tabBar && !tabBar.querySelector('#bookings-tournaments')) {
        _injectTournamentsTab();
      }
    });
    obs.observe(document.body, { childList: true, subtree: true });

    console.log('✅ bmg_final_fix.js loaded — all fixes applied');
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', _boot);
  } else {
    setTimeout(_boot, 0);
  }

})();
