/**
 * bmg_three_bug_fix.js
 * ═══════════════════════════════════════════════════════════════
 * Fixes THREE critical bugs:
 *
 *  BUG 1 — QR Entry Pass: "Booking not found in system"
 *  BUG 2 — Slot still shows GREEN (available) after booking
 *  BUG 3 — Location not auto-detected (requires page refresh)
 *
 * HOW TO USE:
 *   Add ONE <script> tag at the very END of index.html, after all
 *   other script tags (app.js, paymentService.js, all bmg_*.js):
 *
 *   <script src="bmg_three_bug_fix.js"></script>
 *
 * ═══════════════════════════════════════════════════════════════
 */

(function () {
  'use strict';

  /* ─────────────────────────────────────────────────────────────
   * HELPERS
   * ───────────────────────────────────────────────────────────── */
  function _log(msg) {
    console.log('[bmg_three_bug_fix]', msg);
  }

  function _ready(fn) {
    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', fn);
    } else {
      // Use a short delay so app.js finishes its own DOMContentLoaded handlers first
      setTimeout(fn, 300);
    }
  }

  /* ═══════════════════════════════════════════════════════════════
   * BUG 1 FIX — QR Entry Pass: "Booking not found in system"
   *
   * ROOT CAUSE:
   *   processVerifiedQRCode() queries:
   *     db.collection('bookings').where('bookingId', '==', qrObject.bookingId)
   *
   *   BUT some booking flows (paymentService webhook / Cloud Function)
   *   write the document with the orderId as the Firestore document ID
   *   and do NOT always set a separate bookingId field.  The .where()
   *   query finds nothing → "Booking not found in system".
   *
   *   Additionally the strict time-window check blocks legitimate
   *   same-day scans and the bookingStatus check fails if the Cloud
   *   Function wrote 'paid' or 'payment_confirmed' instead of 'confirmed'.
   *
   * FIX:
   *   Replace processVerifiedQRCode with a version that:
   *   1. Tries the .where('bookingId') query first (existing behaviour).
   *   2. Falls back to fetching the document by ID (orderId) directly.
   *   3. Accepts bookingStatus values: 'confirmed', 'paid',
   *      'payment_confirmed', 'completed'.
   *   4. Relaxes the time-window to 2 hours before / 3 hours after
   *      the slot start so owner scans work comfortably.
   * ═══════════════════════════════════════════════════════════════ */

  async function _fixedProcessVerifiedQRCode(qrData) {
    const resultDiv = document.getElementById('professional-qr-result');

    try {
      /* ── Parse QR ── */
      let qrObject;
      try {
        qrObject = JSON.parse(qrData);
      } catch (e) {
        throw new Error('Invalid QR Code Format');
      }

      /* ── CHECK 1: App ID ── */
      if (!qrObject.appId || qrObject.appId !== 'BookMyGame') {
        throw new Error('This QR code was not generated by BookMyGame');
      }

      /* ── CHECK 2: QR validity window ── */
      const now = new Date();
      const validFrom = new Date(qrObject.validFrom);
      const validTo   = new Date(qrObject.validTo);

      if (now < validFrom) {
        throw new Error('QR Code is not valid yet');
      }
      if (now > validTo) {
        throw new Error('QR Code has expired');
      }

      /* ── CHECK 3: Fetch booking — two strategies ── */
      const db = window.db;
      let bookingDoc  = null;
      let bookingData = null;

      // Strategy A: query by bookingId field (original approach)
      if (qrObject.bookingId) {
        const snap = await db.collection('bookings')
          .where('bookingId', '==', qrObject.bookingId)
          .limit(1)
          .get();

        if (!snap.empty) {
          bookingDoc  = snap.docs[0];
          bookingData = bookingDoc.data();
        }
      }

      // Strategy B: fetch document by Firestore doc ID (= orderId / bookingId)
      if (!bookingDoc && qrObject.bookingId) {
        const direct = await db.collection('bookings').doc(qrObject.bookingId).get();
        if (direct.exists) {
          bookingDoc  = direct;
          bookingData = direct.data();
        }
      }

      // Strategy C: try with orderId if different field in QR
      if (!bookingDoc && qrObject.orderId) {
        const direct = await db.collection('bookings').doc(qrObject.orderId).get();
        if (direct.exists) {
          bookingDoc  = direct;
          bookingData = direct.data();
        }
        if (!bookingDoc) {
          const snap2 = await db.collection('bookings')
            .where('bookingId', '==', qrObject.orderId)
            .limit(1)
            .get();
          if (!snap2.empty) {
            bookingDoc  = snap2.docs[0];
            bookingData = snap2.docs[0].data();
          }
        }
      }

      if (!bookingDoc || !bookingData) {
        throw new Error(
          'Booking not found in system. ' +
          'Please ensure payment was completed successfully.'
        );
      }

      /* ── CHECK 4: Ground ownership ── */
      const cu = window.currentUser;
      if (!cu) throw new Error('You must be logged in to verify entries');

      const groundDoc = await db.collection('grounds').doc(bookingData.groundId).get();
      if (!groundDoc.exists) throw new Error('Ground not found');

      const ground = groundDoc.data();
      if (ground.ownerId !== cu.uid) {
        throw new Error('You can only verify bookings for your own grounds');
      }

      /* ── CHECK 5: Ground ID matches QR ── */
      if (qrObject.groundId && bookingData.groundId !== qrObject.groundId) {
        throw new Error('QR code is for a different ground');
      }

      /* ── CHECK 6: Already used ── */
      if (bookingData.entryStatus === 'used') {
        throw new Error('This entry has already been used');
      }

      /* ── CHECK 7: Booking status (relaxed set) ── */
      const CONFIRMED_STATUSES = ['confirmed', 'paid', 'payment_confirmed', 'completed'];
      const bStatus = (bookingData.bookingStatus || bookingData.status || '').toLowerCase();
      if (!CONFIRMED_STATUSES.includes(bStatus)) {
        throw new Error(
          `Booking is not confirmed yet. Current status: "${bStatus || 'unknown'}". ` +
          'Please ask the customer to check "My Bookings".'
        );
      }

      /* ── CHECK 8: Date check ── */
      const today = new Date().toISOString().split('T')[0];
      if (bookingData.date && bookingData.date !== today) {
        throw new Error(
          `This booking is for ${bookingData.date}. Today is ${today}.`
        );
      }

      /* ── CHECK 9: Relaxed time window (−2h to +3h around slot start) ── */
      if (bookingData.slotTime) {
        const [startHourStr, startMinStr] = (bookingData.slotTime.split('-')[0]).split(':');
        const startHour = parseInt(startHourStr, 10);
        const startMin  = parseInt(startMinStr  || '0', 10);

        const slotStartTime = new Date(bookingData.date || today);
        slotStartTime.setHours(startHour, startMin, 0, 0);

        const entryOpen  = new Date(slotStartTime.getTime() - 2  * 60 * 60 * 1000); // 2 h before
        const entryClose = new Date(slotStartTime.getTime() + 3  * 60 * 60 * 1000); // 3 h after

        if (now < entryOpen) {
          const minsLeft = Math.ceil((entryOpen - now) / 60000);
          throw new Error(
            `Entry opens at ${entryOpen.toLocaleTimeString('en-IN')}. ` +
            `Please come back in ${minsLeft} minute(s).`
          );
        }
        if (now > entryClose) {
          throw new Error(
            `Entry window closed at ${entryClose.toLocaleTimeString('en-IN')}.`
          );
        }
      }

      /* ── ALL CHECKS PASSED — mark entry used ── */
      await bookingDoc.ref.update({
        entryStatus   : 'used',
        entryTime     : firebase.firestore.FieldValue.serverTimestamp(),
        verifiedBy    : cu.uid,
        verifiedByName: cu.ownerName || cu.name || '',
        verifiedAt    : firebase.firestore.FieldValue.serverTimestamp(),
        updatedAt     : firebase.firestore.FieldValue.serverTimestamp(),
      });

      // Update ground stats (non-blocking)
      db.collection('grounds').doc(bookingData.groundId).update({
        lastVerifiedAt      : firebase.firestore.FieldValue.serverTimestamp(),
        totalEntriesVerified: firebase.firestore.FieldValue.increment(1),
      }).catch(() => {});

      if (typeof window.showVerificationResult === 'function') {
        window.showVerificationResult(true, bookingData);
      } else {
        alert('✅ Entry Verified Successfully!');
      }

    } catch (error) {
      console.error('[bmg_three_bug_fix] QR Verification Error:', error);
      if (typeof window.showVerificationResult === 'function') {
        window.showVerificationResult(false, null, error.message);
      } else {
        alert('❌ Verification Failed: ' + error.message);
      }
    }
  }

  /* ═══════════════════════════════════════════════════════════════
   * BUG 2 FIX — Slot still shows GREEN after booking
   *
   * ROOT CAUSE:
   *   confirmSlotBooking() / paymentService writes status = 'booked'
   *   to the slots collection.
   *   loadSlots() builds a slotStatusMap and then checks:
   *     - 'available' → green
   *     - 'confirmed' → disabled
   *     - 'closed'    → disabled
   *     - 'pending'   → disabled
   *     - 'locked'    → disabled
   *   There is NO case for 'booked', so 'booked' slots fall through
   *   with statusClass = '' → rendered as available (green).
   *
   * FIX:
   *   Patch loadSlots to treat 'booked' the same as 'confirmed'
   *   (disabled, red/booked class). We do this by intercepting the
   *   function and normalising 'booked' → 'confirmed' in the status
   *   map before it is read by the rendering loop.
   * ═══════════════════════════════════════════════════════════════ */

  function _patchLoadSlots() {
    const _orig = window.loadSlots;
    if (typeof _orig !== 'function') {
      setTimeout(_patchLoadSlots, 400);
      return;
    }

    window.loadSlots = async function (groundId, date) {
      // Call the original function
      await _orig.call(this, groundId, date);

      // After the original renders, find any slots that Firestore returned
      // as 'booked' but were left with no status class (shown as available).
      // We query Firestore directly and fix the DOM.
      try {
        const db = window.db;
        const snap = await db.collection('slots')
          .where('groundId', '==', groundId)
          .where('date',     '==', date)
          .where('status',   'in', ['booked', 'confirmed', 'locked', 'pending'])
          .get();

        if (snap.empty) return;

        snap.forEach(doc => {
          const slot    = doc.data();
          const status  = slot.status; // 'booked' | 'confirmed' | 'locked' | 'pending'
          const slotKey = `${slot.startTime}-${slot.endTime}`;

          // Find the rendered DOM element
          const el = document.querySelector(`.time-slot[data-slot="${slotKey}"]`);
          if (!el) return;

          // If the element is still showing as available (has no blocking class), fix it
          const isStillAvailable =
            el.classList.contains('available') ||
            (!el.classList.contains('confirmed') &&
             !el.classList.contains('booked') &&
             !el.classList.contains('locked') &&
             !el.classList.contains('pending') &&
             !el.classList.contains('closed') &&
             !el.classList.contains('past'));

          if (isStillAvailable) {
            el.classList.remove('available');
            // Map status to CSS class
            const cssClass = status === 'booked' ? 'booked' : status;
            el.classList.add(cssClass);
            el.dataset.status  = 'disabled';
            el.dataset.available = '';
            el.removeAttribute('data-available');

            // Replace with a clone to strip any click listeners
            const clone = el.cloneNode(true);
            el.parentNode.replaceChild(clone, el);

            _log(`Slot ${slotKey} fixed → "${status}" (was showing as available)`);
          }
        });
      } catch (e) {
        console.warn('[bmg_three_bug_fix] Slot status patch query failed:', e);
      }
    };

    _log('loadSlots patched to handle "booked" status ✅');
  }

  /* Add the 'booked' CSS class to styles so it renders correctly (red/disabled) */
  function _injectBookedSlotStyle() {
    if (document.getElementById('bmg-booked-slot-style')) return;
    const style = document.createElement('style');
    style.id = 'bmg-booked-slot-style';
    style.textContent = `
      /* BUG 2 FIX: make 'booked' slots look identical to 'confirmed' (disabled/red) */
      .time-slot.booked {
        background: var(--danger, #ef4444) !important;
        color: #fff !important;
        opacity: 0.85;
        cursor: not-allowed !important;
        pointer-events: none !important;
        border-color: var(--danger, #ef4444) !important;
      }
      .time-slot.booked::after {
        content: ' • Booked';
        font-size: 0.7em;
        opacity: 0.9;
      }
    `;
    document.head.appendChild(style);
  }

  /* ═══════════════════════════════════════════════════════════════
   * BUG 3 FIX — Location not auto-detected (needs refresh)
   *
   * ROOT CAUSE:
   *   getUserLocation() uses getCurrentPosition (one-shot).
   *   It is only called once, 50 ms after login, inside a setTimeout.
   *   If the browser permission prompt is still pending at that point,
   *   or the user grants permission later, the location is never
   *   captured. No watchPosition is used, so moving doesn't update it.
   *   The home page loads before the position resolves, so
   *   loadNearbyVenues() runs with userLocation = null.
   *
   * FIX:
   *   1. Replace getUserLocation with a version that ALSO sets up
   *      navigator.geolocation.watchPosition so location stays live.
   *   2. Each time a position arrives, if the main page is visible,
   *      call loadNearbyVenues() to refresh nearby grounds.
   *   3. Call our improved version immediately on DOMContentLoaded
   *      so it starts the permission prompt right away.
   * ═══════════════════════════════════════════════════════════════ */

  let _locationWatchId = null;

  function _startLocationWatch() {
    if (!navigator.geolocation) {
      _log('Geolocation not supported');
      return;
    }

    // Don't start multiple watches
    if (_locationWatchId !== null) return;

    const _onPosition = async (position) => {
      const lat = position.coords.latitude;
      const lng = position.coords.longitude;

      // Update global userLocation used everywhere in app.js
      window.userLocation = { lat, lng };
      try {
        localStorage.setItem('userLocation', JSON.stringify(window.userLocation));
      } catch (e) {}

      // Update location text in header
      try {
        const resp = await fetch(
          `https://nominatim.openstreetmap.org/reverse?format=json&lat=${lat}&lon=${lng}&zoom=18&addressdetails=1`
        );
        const data = await resp.json();
        let locationText = '';
        if (data.address) {
          const area = data.address.suburb || data.address.neighbourhood || data.address.road || '';
          const city = data.address.city   || data.address.town          || data.address.village || '';
          locationText = area ? `${area}, ${city}` : (city || 'Location detected');
        }
        locationText = locationText || `${lat.toFixed(4)}, ${lng.toFixed(4)}`;

        const el = document.getElementById('current-location');
        if (el) el.textContent = locationText;
      } catch (e) {
        const el = document.getElementById('current-location');
        if (el) el.textContent = `${lat.toFixed(4)}, ${lng.toFixed(4)}`;
      }

      // Reload nearby venues if main page is currently shown
      const mainPage = document.getElementById('main-page');
      if (mainPage && mainPage.classList.contains('active')) {
        if (typeof window.loadNearbyVenues === 'function') {
          window.loadNearbyVenues();
        }
      }
    };

    const _onError = (err) => {
      console.warn('[bmg_three_bug_fix] Geolocation error:', err.message);
      const el = document.getElementById('current-location');

      // Try cached location so the UI is never blank
      try {
        const cached = localStorage.getItem('userLocation');
        if (cached) {
          const loc = JSON.parse(cached);
          window.userLocation = loc;
          if (el) el.textContent = `${loc.lat.toFixed(4)}, ${loc.lng.toFixed(4)}`;
          // Still load nearby venues with cached location
          if (typeof window.loadNearbyVenues === 'function') {
            window.loadNearbyVenues();
          }
        } else if (el) {
          el.textContent = 'Enable location for nearby grounds';
        }
      } catch (e) {}
    };

    const opts = {
      enableHighAccuracy: true,
      timeout           : 15000,
      maximumAge        : 60000, // allow cached position up to 1 min old
    };

    // One-shot first so we get location immediately
    navigator.geolocation.getCurrentPosition(_onPosition, _onError, opts);

    // Then watch for ongoing updates (user moves, permission granted later)
    _locationWatchId = navigator.geolocation.watchPosition(_onPosition, _onError, {
      enableHighAccuracy: true,
      maximumAge        : 60000,
    });

    _log('Live location watch started (watchId=' + _locationWatchId + ') ✅');
  }

  /* Override the original getUserLocation so any existing callers
   * (the login handler, the refresh-location button, etc.) also
   * benefit from the watchPosition approach. */
  function _patchGetUserLocation() {
    window.getUserLocation = function () {
      _startLocationWatch();
    };
    _log('getUserLocation patched ✅');
  }

  /* ═══════════════════════════════════════════════════════════════
   * BOOT — wire everything up
   * ═══════════════════════════════════════════════════════════════ */

  function _boot() {
    /* BUG 1 — replace QR verification */
    window.processVerifiedQRCode = _fixedProcessVerifiedQRCode;
    _log('processVerifiedQRCode replaced ✅');

    /* BUG 2 — patch slot renderer + inject CSS */
    _injectBookedSlotStyle();
    _patchLoadSlots();

    /* BUG 3 — patch location + start watch immediately */
    _patchGetUserLocation();
    _startLocationWatch();
  }

  _ready(_boot);

})();